version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - "rm -f .env"
      - "printenv > .env"      
      - systemctl start docker
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $INFRUSTRUCTURE_NAME .
      - docker tag $INFRUSTRUCTURE_NAME $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' $INFRUSTRUCTURE_NAME $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
