version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - "rm -f .env"
      - "printenv > .env"      
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $INFRUSTRUCTURE_NAME .
      - docker tag $INFRUSTRUCTURE_NAME $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' $INFRUSTRUCTURE_NAME $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
